name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: dist
          branch: static-pages
